name: Frontend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: starter/frontend

jobs:
  lint:
  name: Lint
  runs-on: ubuntu-latest
  steps:
    - name: Checking Out the code from Repo
      uses: actions/checkout@v3

    - name: Setting up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.16.0

    - name: Cache before dependency install
      id: CachingData
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: deps-node-modules-${{ runner.os }}-${{ hashFiles('starter/frontend/**/package-lock.json') }}
      
    - name: Installing dependencies
      run: npm ci

    - name: Linting
      run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checking Out the code from Repo
        uses: actions/checkout@v3

      - name: Setting up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Cache before dependency install
        id: CachingData
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ runner.os }}-${{ hashFiles('starter/frontend/**/package-lock.json') }}
        
      - name: Installing dependencies
        run: npm ci

      - name: Now Running Tests
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checking Out the code from Repo
        uses: actions/checkout@v3

      - name: Building the Image
        run: docker build -t starter/frontend starter/frontend
